cp sudoers /root/sudoers
cp smb.conf /etc/samba/smb.conf
cp krb5.conf /etc/krb5.conf
cp ssh_config /root/ssh_config
cp sshd_config /root/sshd_config
cp common-password /root/common-password
cp ntp.conf /etc/ntp.conf
cp apache-default-ssl /root/apache-default-ssl
cp apache-default /root/apache-default
cp apache-databank-proxy /root/apache-databank-proxy
cp make-apache2-cert.sh /root/make-apache2-cert.sh
cp openssl.cnf /etc/ssl/openssl.cnf
cp nrpe.cfg /root/nrpe.cfg
cp aliases /root/aliases
cp main.cf /root/main.cf
cp common-auth /root/common-auth
cp sources.list /etc/apt/sources.list
cp DATASTAGE.README /root/DATASTAGE.README
cp firstboot.sh /root/firstboot.sh
cp postboot-1.sh /root/postboot-1.sh
cp postboot-2.sh /root/postboot-2.sh
cp postboot-3.sh /root/postboot-3.sh
cp postboot-4.sh /root/postboot-4.sh
cp lvmconfig.sh /root/lvmconfig.sh
cp datastageconfig.sh /root/datastageconfig.sh
cp datastagedatasetup.sh /root/datastagedatasetup.sh
cp datastagedataaccess.sh /root/datastagedataaccess.sh
cp datastagetoolsetup.sh /root/datastagetoolsetup.sh
cp datastageusermanagement.sh /root/datastageusermanagement.sh
cp datastageuseradd.sh /root/datastageuseradd.sh
cp datastageuserdel.sh /root/datastageuserdel.sh
cp datastagemigrateusers.sh /root/datastagemigrateusers.sh
cp apache2.conf /root/apache2.conf