#!/bin/bash

case "$1" in
  start)

  django-admin longliving --settings=datastage.web.settings &

  ;;

  stop)

  django-admin longliving_stop --settings=datastage.web.settings

  ;;

  status)

  ;;
esac
